spring:
  datasource:
    url: jdbc:mysql://localhost:3306/API_Eletrodomestico
    username: root
    password: root123
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show_sql: true
    hibernate:
      ddl-auto: update
